### ISSUE TITLE
Error: ToManyRequests

### ISSUE THREAD

**Issue by Dominik-Kriese** [blaz-blazer/wp-get-products-from-amazon-pa-api-5#1]
Hello,

i tried to use your plugin in a hidden side and used the basic-template to see how the plugin support is working. If I use it or not, i get the same error in both cases, as seen in the picture below:
![grafik](https://user-images.githubusercontent.com/18443158/78931640-899aba00-7aa6-11ea-82c8-daae5a0cb1cc.png)
Do you know if this is an issue with the Plugin or a problem of amazon with them restricting the number of requests?

Best Regards and thanks for your work
Dominik

**Comment by blaz-blazer** [comment]
Hi Dominik, 

this means that Amazon PA API is returning "TooManyRequests" error. You can read more about their efficiency guidelines here: https://webservices.amazon.com/paapi5/documentation/troubleshooting/api-rates.html

Most likely the problem is in one of the following: 
- You haven't generated referring sales for a consecutive 30-day period
- You exceeded the daily limit
- You exceeded the per second limit 

The per second limit is rarely a problem because the plugin stores product info in the database after the first page load (if cache is enabled). Nevertheless, if you have many shortcodes on a single page you might see such an error on some of them after the first page load. But after refreshing the page they should be gone. Afterwards the products are updated via cron job which takes 1 request per second into consideration. So, my guess is that you are having problems with the first or the second point. 

Regards,
Blaz

**Comment by Dominik-Kriese** [comment]
Hello Blaz,

thanks for your response. I will investigate what happend and close this issue, since amazons documentation states, that it is not part of your plugin.

Best Regards
Dominik
